version: "3.3"

services:
  photogallery-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: photogallery-api
    restart: on-failure
    command: sh -c "
      pytest &&
      python manage.py migrate &&
      python manage.py loaddata db.json &&
      python manage.py runserver 0.0.0.0:8000 -v 3"
    volumes:
      - ".:/app/photogallery-api/"
    ports:
      - "8000:8000"
    env_file: .env_local
    depends_on:
      - photogallery-db
      
  photogallery-db:
    image: postgres:14
    container_name: photogallery-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
